name: Docker Image CI

on:
  workflow_dispatch:

jobs:
  build:
    if: ${{ github.ref == "abc" }}
    uses: ./.github/workflows/blank.yml
    with:
      image: "ghcr.io/cafe-chanta"
      tags: "develop"
      tag_suffixes: "-123"
      build-args: |
        A=sabri
        B=yassmine
  build2:
    needs: [build]
    uses: ./.github/workflows/blank.yml
    with:
      image: "ghcr.io/cafe-chanta"
      tags: "develop"
      tag_suffixes: "-123"
      build-args: |
        A=sabri
        B=yassmine
